import { Mars, Shirt, Venus, Glasses } from "lucide-react";
import IconColor from "../utils/IconColor";

export const mockData = {
  categories: ["accessories", "shirts", "pants", "shorts"],

  arrivals: [
    {
      image: "/newArrival-1.png",
      title: "Womens's Section",
      icon: <IconColor icon={<Mars />} color="bg-pink-100" />,
      desc: "Discover the latest arrivals in men's fashion. From casual wear to formal attire, our collection has something for every style.",
    },
    {
      image: "/newArrival-2.png",
      title: "Men's Collection",
      icon: <IconColor icon={<Venus />} color="bg-blue-100" />,
      desc: "Explore the newest trends in men's fashion with our latest collection. From casual wear to formal attire, find the perfect pieces to elevate your style.",
    },
    {
      image: "/newArrival-3.png",
      title: "Accessories",
      icon: <IconColor icon={<Glasses />} color="bg-yellow-100" />,
      desc: "Complete your look with our stylish accessories. From statement jewelry to trendy bags, find the perfect finishing touches for any outfit.",
    },
  ],
  bestSellers: [
    {
      title: "Honey Glasses",
      image: "/BS1.jpg",
      price: "149$",
      tag: ["accessories"],
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Stylish Sunglasses",
      image: "/BS2.jpg",
      price: "119$",
      tag: ["accessories"],
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Blue Sunglasses",
      image: "/BS6.jpg",
      price: "129$",
      tag: ["accessories"],
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Only You Tee",
      image: "/BS3.jpg",
      price: "99$",
      tag: ["shirts", "men", "women"],
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Blessed Tee",
      image: "/BS4.jpg",
      price: "49$",
      tag: ["shirts", "men", "women"],
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Grind Never Stop Tee",
      image: "/BS5.jpg",
      price: "69$",
      tag: ["shirts", "men", "women"],
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
  ],
  wishList: [
    {
      title: "Honey Glasses",
      image: "/BS1.jpg",
      price: "149$",
      tag: ["accessories"],
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Stylish Sunglasses",
      image: "/BS2.jpg",
      price: "119$",
      tag: ["accessories"],
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Blue Sunglasses",
      image: "/BS6.jpg",
      price: "129$",
      tag: ["accessories"],
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Only You Tee",
      image: "/BS3.jpg",
      price: "99$",
      tag: ["shirts", "men", "women"],
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Blessed Tee",
      image: "/BS4.jpg",
      price: "49$",
      tag: ["shirts", "men", "women"],
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      title: "Grind Never Stop Tee",
      image: "/BS5.jpg",
      price: "69$",
      tag: ["shirts", "men", "women"],
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
  ],
};
