import { Mars, Shirt, Venus, Glasses } from "lucide-react";
import IconColor from "../utils/IconColor";

export const mockData = {
  categories: ["accessories", "shirts", "pants", "shorts"],

  products: [
    {
      id: 1,
      title: "Honey Glasses",
      image: "/BS1.jpg",
      price: 149,
      tags: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 2,
      title: "Stylish Sunglasses",
      image: "/BS2.jpg",
      price: 119,
      tags: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 3,
      title: "Blue Sunglasses",
      image: "/BS6.jpg",
      price: 129,
      tags: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 4,
      title: "Only You Tee",
      image: "/BS3.jpg",
      price: 99,
      tags: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 5,
      title: "Blessed Tee",
      image: "/BS4.jpg",
      price: 49,
      tags: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 6,
      title: "Grind Never Stop Tee",
      image: "/BS5.jpg",
      price: 69,
      tags: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ],

  arrivals: [
    {
      image: "/newArrival-1.png",
      title: "Womens's Section",
      icon: <IconColor icon={<Mars />} color="bg-pink-100" />,
      desc: "Discover the latest arrivals in men's fashion. From casual wear to formal attire, our collection has something for every style.",
    },
    {
      image: "/newArrival-2.png",
      title: "Men's Collection",
      icon: <IconColor icon={<Venus />} color="bg-blue-100" />,
      desc: "Explore the newest trends in men's fashion with our latest collection. From casual wear to formal attire, find the perfect pieces to elevate your style.",
    },
    {
      image: "/newArrival-3.png",
      title: "Accessories",
      icon: <IconColor icon={<Glasses />} color="bg-yellow-100" />,
      desc: "Complete your look with our stylish accessories. From statement jewelry to trendy bags, find the perfect finishing touches for any outfit.",
    },
  ],
  bestSellers: [
    {
      id: 1,
      title: "Honey Glasses",
      image: "/BS1.jpg",
      price: 149,
      tag: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 2,
      title: "Stylish Sunglasses",
      image: "/BS2.jpg",
      price: 119,
      tag: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 3,
      title: "Blue Sunglasses",
      image: "/BS6.jpg",
      price: 129,
      tag: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 4,
      title: "Only You Tee",
      image: "/BS3.jpg",
      price: 99,
      tag: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 5,
      title: "Blessed Tee",
      image: "/BS4.jpg",
      price: 49,
      tag: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 6,
      title: "Grind Never Stop Tee",
      image: "/BS5.jpg",
      price: 69,
      tag: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ],
  wishList: [
    {
      id: 1,
      title: "Honey Glasses",
      image: "/BS1.jpg",
      price: 149,
      tag: ["accessories"],
      tags: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      id: 2,
      title: "Stylish Sunglasses",
      image: "/BS2.jpg",
      price: 119,
      tag: ["accessories"],
      tags: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      id: 3,
      title: "Blue Sunglasses",
      image: "/BS6.jpg",
      price: 129,
      tag: ["accessories"],
      tags: ["accessories"],
      category: "accessories",
      icon: <IconColor icon={<Glasses size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      id: 4,
      title: "Only You Tee",
      image: "/BS3.jpg",
      price: 99,
      tag: ["shirts", "men", "women"],
      tags: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      id: 5,
      title: "Blessed Tee",
      image: "/BS4.jpg",
      price: 49,
      tag: ["shirts", "men", "women"],
      tags: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
    {
      id: 6,
      title: "Grind Never Stop Tee",
      image: "/BS5.jpg",
      price: 69,
      tag: ["shirts", "men", "women"],
      tags: ["shirts", "men", "women"],
      category: "shirts",
      icon: <IconColor icon={<Shirt size={30} />} color="bg-black" />,
      rating: 4.5,
    },
  ],
};
